services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - FRONTEND_URL=http://frontend:5173
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - API_KEY=${NVIDIA_API_KEY}
    volumes:
      - ./Backend:/app
      - /app/node_modules
    networks:
      - quickweb_network
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    ports:
      - "5173:5173"
      - "5000:5000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - quickweb_network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  quickweb_network:
    driver: bridge
